vich_uploader:
    db_driver: orm
    mappings:
        picture_file:
            uri_prefix: /uploads
            upload_destination: '%upload_directory%'
            delete_on_update: true
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
        illustration_file:
            uri_prefix: /uploads
            upload_destination: '%upload_directory%'
            delete_on_update: true
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
